version: "3.8"

services:
  tests:
    command: python -m pytest app/tests/
    environment:
      - TSS_ENDPOINT=http://localhost:14141
    build: ./groundcontrol-api
  groundcontrol-api:
    command: sh -c "sleep 5; uvicorn app.main:app --host 0.0.0.0 --port 8181"
    build: ./groundcontrol-api
    depends_on:
      - groundcontrol-db
    ports:
      - 8181:8181
  lmcc:
    build: ./GCSiteTest
    ports:
      - 3000:3000
  groundcontrol-db:
    build: ./groundcontrol-db # use latest official postgres version
    env_file:
      - ./groundcontrol-db/database.env # configure postgres
    ports:
      - "5432:5432"
  tss:
    build: ./TSSExtras
    ports: 
      - 14141:14141
